### ISSUE TITLE
sonar fail

### ISSUE THREAD

**Issue by jhmin128** [f-lab-edu/joo-hee#20]
```
> Task :sonar
Failed to check if project 'f-lab-edu_joo-hee' is bound
Failed to prepare download of the sensor cache
Use of preview features have been detected during analysis. Enable DEBUG mode to see them.
> Task :sonar FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':sonar'.
> Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator to check the permissions of the user the token belongs to
```

**Comment by flab-true** [comment]
@jhmin128 님 secretKey 설정이 누락된 것 같네요. 
아래 사이트에서 개인 계정의 secretKey를 발급 받고, 설정하면 되지 않을까 싶습니다. 한번 확인해 보시겠어요? 
https://sonarcloud.io/account/security
![image](https://github.com/user-attachments/assets/21e0ee10-7e50-4bd5-b051-dba9d10f83c9)

**Comment by flab-true** [comment]
@jhmin128
Github Actions 환경변수 설정이 필요합니다.
Settings에서 가능할 것 같은데요. Settings -> Actions -> new repository secret으로 설정이 가능하지 않을까 싶어요.(저는 Settings에 접속하면 다양한 메뉴가 보이지 않네요)

**Comment by jhmin128** [comment]
@flab-true 
상기 안내된 내용을 모두 다 해봤는데도 같은 오류가 나고 있습니다..
멘토님의 repo 권한을 admin으로 변경하였습니다.

**Comment by flab-true** [comment]
@jhmin128 님 로컬에서 빌드를 수행하면 정상적으로 연동되나요?
circleCi에서 SONAR_TOKEN 환경 변수를 echo로 출력하여 어떻게 나오나요? 정확한 원인을 파악해 보시면 좋겠습니다.

메뉴얼에 따르면 Forked Repository에서 trigger된 workflow는 secrets에 접근할 권한이 없다고 합니다. 이와 같은 현상으로 Secret 정보를 못가지고 오는 건 아닌지 의심스럽네요.
https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
![image](https://github.com/user-attachments/assets/60d0c13b-575d-4282-8503-19fcd1113c40)

**Comment by flab-true** [comment]
https://github.com/orgs/community/discussions/50161 여기 내용을 참고하면, 
[pull_request_target trigger](https://github.com/artis3n/ansible-role-tailscale/blob/main/.github/workflows/pull_request_target.yml) 사용하여 PR 진행을 가이드하고 있네요. [pull_request_target](https://docs.github.com/ko/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks)KR 문서입니다.


이런 기술 블로그도 보입니다. 
https://dev.to/petrsvihlik/using-environment-protection-rules-to-secure-secrets-when-building-external-forks-with-pullrequesttarget-hci

한국 블로그는 아래 내용이 괜찮은 것 같아요.
https://blog.outsider.ne.kr/1541

**Comment by flab-true** [comment]
당장 급해 보이지는 않습니다만, 해당 이슈를 해결하신다면 [여기(wiki)](https://github.com/f-lab-edu/joo-hee/wiki)에 간단하게 정리를 하셔도 좋을 것 같습니다.

**Comment by flab-true** [comment]
SonarIo에 더미 프로젝트를 만들어서 연동을 해보았는데요. 이건 정상적으로 연동되네요. 
Local에서 task(:sonar) 수행했기 때문에 build.gradle 파일에 sonar plugin 추가했고, SonarIo 더미 프로젝트에는 수동 분석 설정 값을 활성화 하도록 조정하였습니다. 
https://sonarcloud.io/project/overview?id=flab-true_joo-hee
![image](https://github.com/user-attachments/assets/e163774a-a37b-48f9-9b7a-28b16a67436d)
![image](https://github.com/user-attachments/assets/6b5cf80a-1151-40e1-85d7-d72df5181034)

**Comment by flab-true** [comment]
@jhmin128 님, sonarcloud의 f-lab-edu에 대한 secret_key 정보가 여기 레포에 기본적으로 설정되어 있었습니다.
일전에 설정을 하시면서 secret_key 값이 개인키로 오버라이딩 되었고, 개인 secret_key로 접근 시 권한이 맞지 않는 오류가 발생되고 있었던 것 같습니다.

추가하신 secret_key 를 삭제하고, 신규 PR에서 정상적으로 연동됨을 확인하였습니다. 
- https://github.com/f-lab-edu/joo-hee/pull/21

forked project에서 PR은  [pull_request_target trigger](https://github.com/artis3n/ansible-role-tailscale/blob/main/.github/workflows/pull_request_target.yml) 방식으로 수정이 필요하기 때문에 작업 방식은 선택해 주시면 될 것 같아요.
